/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Ajouter;

import Controller.Java_projet;

/**
 *
 * @author alex_
 */
public class Ajouter extends javax.swing.JFrame {

    /**
     * Creates new form FAjouter
     */
    public Ajouter() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AjouterPersonne = new javax.swing.JButton();
        AjouterAnnee = new javax.swing.JButton();
        AjouterBulletin = new javax.swing.JButton();
        AjouterClasse = new javax.swing.JButton();
        AjouterDiscipline = new javax.swing.JButton();
        AjouterEnseignement = new javax.swing.JButton();
        AjouterEvaluation = new javax.swing.JButton();
        AjouterInscription = new javax.swing.JButton();
        AjouterNiveau = new javax.swing.JButton();
        AjouterTrimestre = new javax.swing.JButton();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AjouterPersonne.setText("Personne");
        AjouterPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterPersonneActionPerformed(evt);
            }
        });

        AjouterAnnee.setText("Annee");
        AjouterAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterAnneeActionPerformed(evt);
            }
        });

        AjouterBulletin.setText("Bulletin");
        AjouterBulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterBulletinActionPerformed(evt);
            }
        });

        AjouterClasse.setText("Classe");
        AjouterClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterClasseActionPerformed(evt);
            }
        });

        AjouterDiscipline.setText("Discipline");
        AjouterDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterDisciplineActionPerformed(evt);
            }
        });

        AjouterEnseignement.setText("Enseignement");
        AjouterEnseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEnseignementActionPerformed(evt);
            }
        });

        AjouterEvaluation.setText("Evaluation");
        AjouterEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterEvaluationActionPerformed(evt);
            }
        });

        AjouterInscription.setText("Inscription");
        AjouterInscription.setToolTipText("");
        AjouterInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterInscriptionActionPerformed(evt);
            }
        });

        AjouterNiveau.setText("Niveau");
        AjouterNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterNiveauActionPerformed(evt);
            }
        });

        AjouterTrimestre.setText("Trimestre");
        AjouterTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterTrimestreActionPerformed(evt);
            }
        });

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(AjouterPersonne)
                        .addGap(18, 18, 18)
                        .addComponent(AjouterAnnee)
                        .addGap(18, 18, 18)
                        .addComponent(AjouterBulletin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AjouterClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterDiscipline)
                        .addGap(18, 18, 18)
                        .addComponent(AjouterEnseignement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterEvaluation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterInscription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterNiveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AjouterTrimestre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(retour)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjouterPersonne)
                    .addComponent(AjouterAnnee)
                    .addComponent(AjouterBulletin)
                    .addComponent(AjouterClasse)
                    .addComponent(AjouterDiscipline)
                    .addComponent(AjouterEnseignement)
                    .addComponent(AjouterEvaluation)
                    .addComponent(AjouterInscription)
                    .addComponent(AjouterNiveau)
                    .addComponent(AjouterTrimestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(retour)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterPersonneActionPerformed
        this.dispose();
        AjouterPersonne fenetre2=new AjouterPersonne();
        fenetre2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AjouterPersonneActionPerformed

    private void AjouterAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterAnneeActionPerformed
        this.dispose();
        AjouterAnnee fenetre3=new AjouterAnnee();
        fenetre3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterAnneeActionPerformed

    private void AjouterBulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterBulletinActionPerformed
        this.dispose();
        AjouterBulletin fenetre4=new AjouterBulletin();
        fenetre4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterBulletinActionPerformed

    private void AjouterClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterClasseActionPerformed
        this.dispose();
        AjouterClasse fenetre5=new AjouterClasse();
        fenetre5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterClasseActionPerformed

    private void AjouterDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterDisciplineActionPerformed
        this.dispose();
        AjouterDiscipline fenetre6=new AjouterDiscipline();
        fenetre6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterDisciplineActionPerformed

    private void AjouterEnseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEnseignementActionPerformed
        this.dispose();
        AjouterEnseignement fenetre7=new AjouterEnseignement();
        fenetre7.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterEnseignementActionPerformed

    private void AjouterEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterEvaluationActionPerformed
        this.dispose();
        AjouterEvaluation fenetre8=new AjouterEvaluation();
        fenetre8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterEvaluationActionPerformed

    private void AjouterInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterInscriptionActionPerformed
        this.dispose();
        AjouterInscription fenetre9=new AjouterInscription();
        fenetre9.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterInscriptionActionPerformed

    private void AjouterNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterNiveauActionPerformed
        this.dispose();
        AjouterNiveau fenetre10=new AjouterNiveau();
        fenetre10.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterNiveauActionPerformed

    private void AjouterTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterTrimestreActionPerformed
        this.dispose();
        AjouterTrimestre fenetre11=new AjouterTrimestre();
        fenetre11.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AjouterTrimestreActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        this.dispose();
        Java_projet fentre0 = new Java_projet();        // TODO add your handling code here:
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterAnnee;
    private javax.swing.JButton AjouterBulletin;
    private javax.swing.JButton AjouterClasse;
    private javax.swing.JButton AjouterDiscipline;
    private javax.swing.JButton AjouterEnseignement;
    private javax.swing.JButton AjouterEvaluation;
    private javax.swing.JButton AjouterInscription;
    private javax.swing.JButton AjouterNiveau;
    private javax.swing.JButton AjouterPersonne;
    private javax.swing.JButton AjouterTrimestre;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
}
