/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Delete;

/**
 *
 * @author alex_
 */
public class Supprimer extends javax.swing.JFrame {

    /**
     * Creates new form Supprimer
     */
    public Supprimer() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupprimerEnseignement = new javax.swing.JButton();
        SupprimerEvaluation = new javax.swing.JButton();
        SupprimerPersonne = new javax.swing.JButton();
        SupprimerInscription = new javax.swing.JButton();
        SupprimerNiveau = new javax.swing.JButton();
        SupprimerAnnee = new javax.swing.JButton();
        SupprimerTrimestre = new javax.swing.JButton();
        SupprimerBulletin = new javax.swing.JButton();
        SupprimerClasse = new javax.swing.JButton();
        SupprimerDiscipline = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SupprimerEnseignement.setText("Enseignement");
        SupprimerEnseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerEnseignementActionPerformed(evt);
            }
        });

        SupprimerEvaluation.setText("Evaluation");
        SupprimerEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerEvaluationActionPerformed(evt);
            }
        });

        SupprimerPersonne.setText("Personne");
        SupprimerPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerPersonneActionPerformed(evt);
            }
        });

        SupprimerInscription.setText("Inscription");
        SupprimerInscription.setToolTipText("");
        SupprimerInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerInscriptionActionPerformed(evt);
            }
        });

        SupprimerNiveau.setText("Niveau");
        SupprimerNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerNiveauActionPerformed(evt);
            }
        });

        SupprimerAnnee.setText("Annee");
        SupprimerAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerAnneeActionPerformed(evt);
            }
        });

        SupprimerTrimestre.setText("Trimestre");
        SupprimerTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerTrimestreActionPerformed(evt);
            }
        });

        SupprimerBulletin.setText("Bulletin");
        SupprimerBulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBulletinActionPerformed(evt);
            }
        });

        SupprimerClasse.setText("Classe");
        SupprimerClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerClasseActionPerformed(evt);
            }
        });

        SupprimerDiscipline.setText("Discipline");
        SupprimerDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerDisciplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SupprimerPersonne)
                .addGap(18, 18, 18)
                .addComponent(SupprimerAnnee)
                .addGap(18, 18, 18)
                .addComponent(SupprimerBulletin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SupprimerClasse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupprimerDiscipline)
                .addGap(18, 18, 18)
                .addComponent(SupprimerEnseignement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupprimerEvaluation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupprimerInscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupprimerNiveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupprimerTrimestre)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupprimerPersonne)
                    .addComponent(SupprimerAnnee)
                    .addComponent(SupprimerBulletin)
                    .addComponent(SupprimerClasse)
                    .addComponent(SupprimerDiscipline)
                    .addComponent(SupprimerEnseignement)
                    .addComponent(SupprimerEvaluation)
                    .addComponent(SupprimerInscription)
                    .addComponent(SupprimerNiveau)
                    .addComponent(SupprimerTrimestre))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SupprimerEnseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerEnseignementActionPerformed
        this.dispose();
        SupprimerEnseignement fenetre7=new SupprimerEnseignement();
        fenetre7.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SupprimerEnseignementActionPerformed

    private void SupprimerEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerEvaluationActionPerformed
        this.dispose();
        SupprimerEvaluation fenetre8=new SupprimerEvaluation();
        fenetre8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerEvaluationActionPerformed

    private void SupprimerPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerPersonneActionPerformed
        this.dispose();
        SupprimerPersonne fenetre2=new SupprimerPersonne(); 
        fenetre2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerPersonneActionPerformed

    private void SupprimerInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerInscriptionActionPerformed
        this.dispose();
        SupprimerInscription fenetre9=new SupprimerInscription();// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerInscriptionActionPerformed

    private void SupprimerNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerNiveauActionPerformed
        this.dispose();
        SupprimerNiveau fenetre10=new SupprimerNiveau();
        fenetre10.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerNiveauActionPerformed

    private void SupprimerAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerAnneeActionPerformed
        this.dispose();
        SupprimerAnnee fenetre3=new SupprimerAnnee();
        fenetre3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerAnneeActionPerformed

    private void SupprimerTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerTrimestreActionPerformed
        this.dispose();
        SupprimerTrimestre fenetre11=new SupprimerTrimestre();
        fenetre11.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerTrimestreActionPerformed

    private void SupprimerBulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBulletinActionPerformed
        this.dispose();
        SupprimerBulletin fenetre4=new SupprimerBulletin();
        fenetre4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerBulletinActionPerformed

    private void SupprimerClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerClasseActionPerformed
        this.dispose();
        SupprimerClasse fenetre5=new SupprimerClasse();
        fenetre5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerClasseActionPerformed

    private void SupprimerDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerDisciplineActionPerformed
        this.dispose();
        SupprimerDiscipline fenetre6=new SupprimerDiscipline();
        fenetre6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_SupprimerDisciplineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supprimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SupprimerAnnee;
    private javax.swing.JButton SupprimerBulletin;
    private javax.swing.JButton SupprimerClasse;
    private javax.swing.JButton SupprimerDiscipline;
    private javax.swing.JButton SupprimerEnseignement;
    private javax.swing.JButton SupprimerEvaluation;
    private javax.swing.JButton SupprimerInscription;
    private javax.swing.JButton SupprimerNiveau;
    private javax.swing.JButton SupprimerPersonne;
    private javax.swing.JButton SupprimerTrimestre;
    // End of variables declaration//GEN-END:variables
}
