/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Update;

/**
 *
 * @author alex_
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateTrimestre = new javax.swing.JButton();
        UpdateBulletin = new javax.swing.JButton();
        UpdateClasse = new javax.swing.JButton();
        UpdateDiscipline = new javax.swing.JButton();
        UpdateEnseignement = new javax.swing.JButton();
        UpdateEvaluation = new javax.swing.JButton();
        UpdatePersonne = new javax.swing.JButton();
        UpdateInscription = new javax.swing.JButton();
        UpdateNiveau = new javax.swing.JButton();
        UpdateAnnee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpdateTrimestre.setText("Trimestre");
        UpdateTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTrimestreActionPerformed(evt);
            }
        });

        UpdateBulletin.setText("Bulletin");
        UpdateBulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBulletinActionPerformed(evt);
            }
        });

        UpdateClasse.setText("Classe");
        UpdateClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClasseActionPerformed(evt);
            }
        });

        UpdateDiscipline.setText("Discipline");
        UpdateDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDisciplineActionPerformed(evt);
            }
        });

        UpdateEnseignement.setText("Enseignement");
        UpdateEnseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEnseignementActionPerformed(evt);
            }
        });

        UpdateEvaluation.setText("Evaluation");
        UpdateEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEvaluationActionPerformed(evt);
            }
        });

        UpdatePersonne.setText("Personne");
        UpdatePersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePersonneActionPerformed(evt);
            }
        });

        UpdateInscription.setText("Inscription");
        UpdateInscription.setToolTipText("");
        UpdateInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInscriptionActionPerformed(evt);
            }
        });

        UpdateNiveau.setText("Niveau");
        UpdateNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateNiveauActionPerformed(evt);
            }
        });

        UpdateAnnee.setText("Annee");
        UpdateAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAnneeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(UpdatePersonne)
                .addGap(18, 18, 18)
                .addComponent(UpdateAnnee)
                .addGap(18, 18, 18)
                .addComponent(UpdateBulletin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateClasse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateDiscipline)
                .addGap(18, 18, 18)
                .addComponent(UpdateEnseignement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateEvaluation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateInscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateNiveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateTrimestre)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePersonne)
                    .addComponent(UpdateAnnee)
                    .addComponent(UpdateBulletin)
                    .addComponent(UpdateClasse)
                    .addComponent(UpdateDiscipline)
                    .addComponent(UpdateEnseignement)
                    .addComponent(UpdateEvaluation)
                    .addComponent(UpdateInscription)
                    .addComponent(UpdateNiveau)
                    .addComponent(UpdateTrimestre))
                .addContainerGap(369, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTrimestreActionPerformed
        this.dispose();
        UpdateTrimestre fenetre11=new UpdateTrimestre();
        fenetre11.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateTrimestreActionPerformed

    private void UpdateBulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBulletinActionPerformed
        this.dispose();
        UpdateBulletin fenetre4=new UpdateBulletin();
        fenetre4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateBulletinActionPerformed

    private void UpdateClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClasseActionPerformed
        this.dispose();
        UpdateClasse fenetre5=new UpdateClasse();
        fenetre5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateClasseActionPerformed

    private void UpdateDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDisciplineActionPerformed
        this.dispose();
        UpdateDiscipline fenetre6=new UpdateDiscipline();
        fenetre6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateDisciplineActionPerformed

    private void UpdateEnseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEnseignementActionPerformed
        this.dispose();
        UpdateEnseignement fenetre7=new UpdateEnseignement();
        fenetre7.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateEnseignementActionPerformed

    private void UpdateEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEvaluationActionPerformed
        this.dispose();
        UpdateEvaluation fenetre8=new UpdateEvaluation();
        fenetre8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateEvaluationActionPerformed

    private void UpdatePersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePersonneActionPerformed
        this.dispose();
        UpdatePersonne fenetre2=new UpdatePersonne();
        fenetre2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdatePersonneActionPerformed

    private void UpdateInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInscriptionActionPerformed
        this.dispose();
        UpdateInscription fenetre9=new UpdateInscription();
        fenetre9.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateInscriptionActionPerformed

    private void UpdateNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateNiveauActionPerformed
        this.dispose();
        UpdateNiveau fenetre10=new UpdateNiveau();
        fenetre10.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateNiveauActionPerformed

    private void UpdateAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAnneeActionPerformed
        this.dispose();
        UpdateAnnee fenetre3=new UpdateAnnee();
        fenetre3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_UpdateAnneeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateAnnee;
    private javax.swing.JButton UpdateBulletin;
    private javax.swing.JButton UpdateClasse;
    private javax.swing.JButton UpdateDiscipline;
    private javax.swing.JButton UpdateEnseignement;
    private javax.swing.JButton UpdateEvaluation;
    private javax.swing.JButton UpdateInscription;
    private javax.swing.JButton UpdateNiveau;
    private javax.swing.JButton UpdatePersonne;
    private javax.swing.JButton UpdateTrimestre;
    // End of variables declaration//GEN-END:variables
}
