/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Afficher;

import Controller.Java_projet;

/**
 *
 * @author alex_
 */
public class Afficher extends javax.swing.JFrame {

    /**
     * Creates new form Afficher
     */
    public Afficher() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AfficherEnseignement = new javax.swing.JButton();
        AfficherEvaluation = new javax.swing.JButton();
        AfficherPersonne = new javax.swing.JButton();
        AfficherInscription = new javax.swing.JButton();
        AfficherNiveau = new javax.swing.JButton();
        AfficherAnnee = new javax.swing.JButton();
        AfficherTrimestre = new javax.swing.JButton();
        AfficherBulletin = new javax.swing.JButton();
        AfficherClasse = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        AfficherDiscipline = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AfficherEnseignement.setText("Enseignement");
        AfficherEnseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherEnseignementActionPerformed(evt);
            }
        });

        AfficherEvaluation.setText("Evaluation");
        AfficherEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherEvaluationActionPerformed(evt);
            }
        });

        AfficherPersonne.setText("Personne");
        AfficherPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherPersonneActionPerformed(evt);
            }
        });

        AfficherInscription.setText("Inscription");
        AfficherInscription.setToolTipText("");
        AfficherInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherInscriptionActionPerformed(evt);
            }
        });

        AfficherNiveau.setText("Niveau");
        AfficherNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherNiveauActionPerformed(evt);
            }
        });

        AfficherAnnee.setText("Annee");
        AfficherAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherAnneeActionPerformed(evt);
            }
        });

        AfficherTrimestre.setText("Trimestre");
        AfficherTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherTrimestreActionPerformed(evt);
            }
        });

        AfficherBulletin.setText("Bulletin");
        AfficherBulletin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherBulletinActionPerformed(evt);
            }
        });

        AfficherClasse.setText("Classe");
        AfficherClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherClasseActionPerformed(evt);
            }
        });

        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        AfficherDiscipline.setText("Discipline");
        AfficherDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherDisciplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(AfficherPersonne)
                        .addGap(18, 18, 18)
                        .addComponent(AfficherAnnee)
                        .addGap(18, 18, 18)
                        .addComponent(AfficherBulletin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AfficherClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AfficherDiscipline)
                        .addGap(18, 18, 18)
                        .addComponent(AfficherEnseignement)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AfficherEvaluation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AfficherInscription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AfficherNiveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AfficherTrimestre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(461, 461, 461)
                        .addComponent(retour)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AfficherPersonne)
                    .addComponent(AfficherAnnee)
                    .addComponent(AfficherBulletin)
                    .addComponent(AfficherClasse)
                    .addComponent(AfficherDiscipline)
                    .addComponent(AfficherEnseignement)
                    .addComponent(AfficherEvaluation)
                    .addComponent(AfficherInscription)
                    .addComponent(AfficherNiveau)
                    .addComponent(AfficherTrimestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(retour)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AfficherEnseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherEnseignementActionPerformed
        this.dispose();
        AfficherEnseignement fenetre7=new AfficherEnseignement();
        fenetre7.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherEnseignementActionPerformed

    private void AfficherEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherEvaluationActionPerformed
        this.dispose();
        AfficherEvaluation fenetre8=new AfficherEvaluation();
        fenetre8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherEvaluationActionPerformed

    private void AfficherPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherPersonneActionPerformed
        this.dispose();
        AfficherPersonne fenetre2=new AfficherPersonne();
        fenetre2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AfficherPersonneActionPerformed

    private void AfficherInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherInscriptionActionPerformed
        this.dispose();
        AfficherInscription fenetre9=new AfficherInscription();
        fenetre9.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherInscriptionActionPerformed

    private void AfficherNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherNiveauActionPerformed
        this.dispose();
        AfficherNiveau fenetre10=new AfficherNiveau();
        fenetre10.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherNiveauActionPerformed

    private void AfficherAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherAnneeActionPerformed
        this.dispose();
        AfficherAnnee fenetre3=new AfficherAnnee();
        fenetre3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherAnneeActionPerformed

    private void AfficherTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherTrimestreActionPerformed
        this.dispose();
        AfficherTrimestre fenetre11=new AfficherTrimestre();
        fenetre11.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherTrimestreActionPerformed

    private void AfficherBulletinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherBulletinActionPerformed
        this.dispose();
        AfficherBulletin fenetre4=new AfficherBulletin();
        fenetre4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherBulletinActionPerformed

    private void AfficherClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherClasseActionPerformed
        this.dispose();
        AfficherClasse fenetre5=new AfficherClasse();
        fenetre5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherClasseActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        this.dispose();
        Java_projet fentre0 = new Java_projet();        // TODO add your handling code here:
    }//GEN-LAST:event_retourActionPerformed

    private void AfficherDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherDisciplineActionPerformed
        this.dispose();
        AfficherDiscipline fenetre6=new AfficherDiscipline();
        fenetre6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AfficherDisciplineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afficher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afficher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afficher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afficher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afficher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AfficherAnnee;
    private javax.swing.JButton AfficherBulletin;
    private javax.swing.JButton AfficherClasse;
    private javax.swing.JButton AfficherDiscipline;
    private javax.swing.JButton AfficherEnseignement;
    private javax.swing.JButton AfficherEvaluation;
    private javax.swing.JButton AfficherInscription;
    private javax.swing.JButton AfficherNiveau;
    private javax.swing.JButton AfficherPersonne;
    private javax.swing.JButton AfficherTrimestre;
    private javax.swing.JButton retour;
    // End of variables declaration//GEN-END:variables
}
